NIE_day3completed/NIE_3/CSE/urls.py
from django.urls import path
from CSE import views

from CSE.views import StuList,Forms, StudentDetail, StudentUpdate, StudentDelete

app_name = 'CSE'

urlpatterns = [
 path('index', views.index, name = 'index'),
path('products', views.products, name = 'products'),
path('service', views.service, name = 'service'),
path('contacts', views.contacts, name = 'contacts'),
path('basic', views.basic, name = 'basic'),
path('student', views.student, name = 'student'),


path('', StuList.as_view(), name = 'list'),
path('forms', Forms.as_view(), name = 'forms'),
path('<pk>/detail', StudentDetail.as_view(), name = 'detail'),
path('<pk>/update', StudentUpdate.as_view(), name = 'update'),
path('<pk>/delete', StudentDelete.as_view(), name = 'delete'),  

]

NIE_day3completed/NIE_3/CSE/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'index.html')

def products(request):
    name = 'raju'
    department = 'CSE'
    college_name = 'NIE'
    roll_number = 60145
    context = {'name': name, 'c_name': college_name, 'd_name': department, 'r_number':roll_number}
    return render(request,'products.html', context)

def service(request):
    return render(request,'service.html')

def contacts(request):
    return render(request,'contacts.html')


def basic(request):
    return render(request,'basic.html')


from CSE.models import Student
def student(request):
    students = Student.objects.all()
    context = {'students': students}
    return render(request,'student.html',context)


# CBV

from CSE.models import Student
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

class StuList(ListView):
    model = Student
    template_name = 'CBV/list.html'


class Forms(CreateView):
    model = Student
    fields = "__all__"
    template_name = 'CBV/forms.html'
    success_url = '/'


class StudentDetail(DetailView):
    model = Student
    template_name = 'CBV/detail.html'

class StudentUpdate(UpdateView):
    model = Student
    fields = '__all__'
    template_name = 'CBV/update.html'
    success_url = '/'


class StudentDelete(DeleteView):
    model = Student
    template_name = 'CBV/delete.html'
    success_url = '/'




NIE_day3completed/NIE_3/templates/basic.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django_web development</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
   
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'CSE:index' %}">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'CSE:index' %}">Home</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'CSE:products' %}">Products</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="{% url 'CSE:service' %}">Service</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="{% url 'CSE:contacts' %}">Contacts</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'CSE:student' %}">FBV-Student</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'CSE:list' %}">CBV-Student</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'CSE:forms' %}">Student Apply</a>
              </li>
              
                          
          </div>
        </div>
      </nav>


    </nav> 

    {% block content %}

    {% endblock %}




    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

NIE_day3completed/NIE_3/templates/student.html

{% extends 'basic.html' %}

{% block content %}
<h1>This is a student page.</h1>

<ul>
    {% for student in students %}
    <li>{{student.id}}</li>
    <li>{{student.name}}</li>
    <li>{{student.depatment}}</li>
    <li>{{student.college_name}}</li>
    <li>{{student.rollnumber}}</li><hr>   
    {% endfor %}
</ul>

{% endblock %}